
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Sucursales</h1>
          <p class="mb-4">Listado con todos las Sucursales disponibles</a>.</p>

        <div class="row">
          <div class="col-md-4">
            <form class="bg-white shadow p-2" id="addSucursal">
              <h5 class="border-bottom p-2">Agregar Sucursal</h5>

              <div class="form-group">
                <label for="nombreSuc">Nombre</label>
                <input type="text" name="nombreSuc" id="nombreSuc" class="form-control" placeholder="Nombre" required>
              </div>

              <div class="form-group">
                <label for="direccionSuc">Direccion</label>
                <input type="text" name="direccionSuc" id="direccionSuc" class="form-control" placeholder="Direccion" required>
              </div>

              <div class="form-group">
                <label for="telefonoSuc">Telefono</label>
                <input type="text" name="telefonoSuc" id="telefonoSuc" class="form-control" placeholder="Telefono" required>
              </div>

              <div class="form-group">
                <label for="correoSuc">Correo</label>
                <input type="text" name="correoSuc" id="correoSuc" class="form-control" placeholder="Correo" required>
              </div>


              <div class="form-group">
                <input type="submit" value="Agregar" class="btn-block btn btn-primary">
              </div>
            </form>
          </div>

          <!-- DataTales Example -->
          <div class="card shadow mb-4 col-md-8">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Sucursales</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>Nombre</th>
                      <th>Direccion</th>
                      <th>Telefono</th>
                      <th>Actualizar</th>
                      <th>Eliminar</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Id</th>
                      <th>Nombre</th>
                      <th>Direccion</th>
                      <th>Telefono</th>
                      <th>Actualizar</th>
                      <th>Eliminar</th>
                    </tr>
                  </tfoot>
                  <tbody>

                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
