<div class="row">
    <div class="col-md-8 m-auto shadow row">
        <div class="col-md-12 h2 p-3 my-2 bg-white border-bottom-primary text-dark">Agregar Categoria</div>
        <form method="POST" class="col-md-12 p-3">
            <div class="form-group">
                <label for="nombre" class="text-dark">Nombre</label>
                <input type="text" name="catNombre" id="nombre" class="form-control" required placeholder="nombre de la descripcion">
            </div>
            <div class="form-group">
                <label for="descripcion" class="text-dark">Descripcion</label>
                <input type="text" name="catDescripcion" id="descripcion" class="form-control" required placeholder="breve descripcion">
            </div>
            <div class="form-group">
                <input type="submit" name="Agregar" value="Agregar Categoria" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>