<div class="container-fluid row">
    <div class="col-md-12 bg-white p-3 text-center border-bottom d-flex justify-content-around">
        <h2>Productos por Categoria</h2>
        <p class="mb-4 d-flex">
            <a href="<?= BASE_URL ?>categoria/addCategoria" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-file"></i>
            </span>
            <span class="text">Agregar Categoria</span>
            </a>
        </p>

        <p class="mb-4 d-flex">
            <a href="<?= BASE_URL ?>categoria/showAll" class="btn btn-info btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-eye"></i>
            </span>
            <span class="text">Ver Categorias</span>
            </a>
        </p>
    </div>

    <div class="col-md-9">
        <div class="productosFiltrados p-1 row">
            <?= $this->productos ?>
        </div>
    </div>
    <div class="col-md-3 bg-white border-left">
        <h6 class="p-2 m-2 font-weight-bold text-center bg-white">Categorias</h6>
        <ul class="list-unstyled m-2 p-2 bg-white">
            <li class="border-bottom p-1"><a href="#" data-filter="*" class="text-decoration-none filtrar">All</a></li>
            <?= $this->lista ?>
        </ul>
    </div>
</div>