
<!-- Page Heading -->
<h1 class="h4 mb-2 text-gray-800 border-bottom p-3">Agregar Productos</h1>
  <div class="d-flex justify-content-center align-content-center border">
    <form action="" method="post" class="form w-100 row p-3 bg-wite" enctype="multipart/form-data">
      <input type="hidden" name="add" value="1">

      <div class="form-group col-md-6">
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" id="nombre" class="form-control" placeholder="Nombre" required>
      </div>
      
      <div class="form-group col-md-6">
        <label for="description">Descripcion</label>
        <input type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Descripcion" required>
      </div>
      
      <div class="form-group col-md-6">
        <label for="precio">Precio</label>
        <input type="text" name="precio" id="precio" class="form-control" placeholder="Precio" required>
      </div>

      <div class="form-group col-md-6">
        <label for="Proveedor">Proveedor</label>
        <select name="proveedor" id="proveedor" class="form-control chosen">
          <?=$this->prov?>
        </select>
      </div>

      <div class="form-group col-md-6">
        <label for="opcion">Categoria</label>
        <select name="opcion" id="opcion" class="form-control chosen">
          <?= $this->cat ?>
        </select>
      </div>

      <div class="form-group col-md-6">
        <label for="uni">Unidad de medida</label>
        <select name="uni" id="uni" class="form-control chosen">
          <?= $this->unid ?>
        </select>
      </div>

      <div class="form-group col-md-6">
        <label for="precio">Cantidad</label>
        <input type="number" name="cantidad" id="cantidad" class="form-control" placeholder="Cantidad" min="1" required>
      </div>

      <div class="form-group col-md-6">
        <label for="archivo">Imagen</label>
        <input type="file" name="archivo" id="archivo" class="form-control">
      </div>  

      <div class="col-md-12">
        <input type="submit" value="Agregar" class="btn btn-primary">
      </div>
      
    </form>
  </div>
