
          <!-- Page Heading -->
        <div class="row">
          <div class="col-md-9">
            <h1 class="h3 mb-2 text-gray-800">Productos</h1>
            <p class="mb-4">Inventario</p>
          </div>

          <div class="col-md-3">
            <p class="mb-4 d-flex justify-content-end">
              <a href="<?= BASE_URL ?>productos/add" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                  <i class="fas fa-file"></i>
                </span>
                <span class="text">Agregar Producto</span>
              </a>
            </p>
          </div>
        </div>
          <!-- <p class="mb-4">En este modulo se refleja la informacion general de los Productos del sistema.</p> -->
    

          <!-- Page Heading -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary"><?= $this->titulo ?></h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered text-center text-gray-800 text-md nuevosProductos" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Nombre</th>
                      <th>Descripcion</th>
                      <th>Precio Unitario</th>
                      <th>Proveedor</th>
                      <th>Cantidad</th>                      
                      <th class="no-exportar">Imagen</th>
                      <th class="no-exportar">Actualizar</th>
                      <th class="no-exportar">Eliminar</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                    <?= $this->contenido ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
           <!-- Logout Modal-->
  <div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <form class="Editar" enctype="multipart/form-data">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Actualizar Producto</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>

          <div class="modal-body row">
              
              <div class="form-group col-md-6 m-auto">
                <img src="" id="img" class="mt-3 img-fluid w-100">
              </div>    
              <input type="hidden" name="id" id="id">
              <input type="hidden" name="ruta" value="<?= BASE_URL?>" id="ruta">
              <div class="form-group col-md-6">
                <label for="nombre">Nombre</label><input type="text" name="nombre" id="nombre" class="form-control" placeholder="Name">
                <label for="description">Descripcion</label><input type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Description">
                <label for="precio">Precio Unitario</label><input type="text" name="precio" id="precio" class="form-control" placeholder="Price">
              
                 <label for="proveedor">Proveedor</label>
                <input type="hidden" id="proveedor" name="proveedor" class="form-control" readonly>
                <input type="text" id="proveedorname" class="form-control" readonly>
              </div>
  
              <div class="col-md-6 form-group">
                <label for="Categoria">Categoria Actual</label>
                <input type="text" readonly class="form-control" id="catActual" name="catActual">
              </div>

              <input type="hidden" name="nomImgAnt" id="nomImgAnt">

              <div class="form-group col-md-6">
                <label for="archivo">Cambiar Imagen</label>
                <input type="file" name="archivo" id="archivo" class="form-control">
            </div> 

          </div>

          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  </div>


  