<div class="container-fluid" style="height: 60vh">
    <h2 class="col-md-12 text-center">Login to your account</h2>
    <div class="col-md-12">
        <form class="border form-style" id="loginUserPublic" method="POST" style="width:40%;margin:auto">
            <div class="form-group">
                <label for="correoUser"><span class="fa fa-user"></span> Usuario</label>
                <input type="text" name="loginClienteUser" id="loginClienteUser" class="form-control" placeholder="Email or Username" required autocomplete="off">
            </div>
            <div class="form-group">
                <label for="passwordUser"><span class="fa fa-key"></span> Password</label>
                <input type="password" name="loginClientePass" id="loginClientePass" class="form-control" placeholder="Password" required autocomplete="off">
            </div>
            <div class="form-grou">
                <button type="submit" class="btn btn-default">Ingresar</button>
                <a href="<?= BASE_URL ?>registro" style="display:block;margin: 10px;">Crear una cuenta?</a>
            </div>
            <div class="errLogin"><?= $this->errLog?></div>
        </form>
    </div>
</div>
