
<section>
	<div class="container">
		<div class="row">
            <?= $this->categorias ?>    

            <div class="col-sm-9">
                <div class="detalle_producto row"><!--product-details-->

                    <?= $this->detalle ?>

                    <div class="recommended_items col-md-12" style="margin-top:2rem;"><!--recommended_items-->
                        <h2 class="title text-center">Productos recomendados</h2>
                        
                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active">
                                    <?= $this->recomendacion?>
                                </div>
                                <div class="item">
                                    <?= $this->recomendacion?>	
                                </div>
                            </div>
                                <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                                </a>
                                <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                                </a>			
                        </div>
                    </div><!--/recommended_items-->
                </div>
			</div>
        </div>
    </div>
</section>