<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 padding-right">
                <div class="features_items">
                    <!--features_items-->
                    <h2 class="h1">Categoria: <?=$this->catAll[0]['cat_product_nombre']?></h2>
                    <hr>

                    <div class="row">
                         <?=$this->all?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
