 <!-- Page Heading -->
 <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Clientes</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered text-center text-gray-800 text-md nuevosProductos" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Cedula</th>
                      <th>Nombres</th>
                      <th>Apellidos</th>
                      <th>Telefono</th>
                      <th>Direccion</th>
                      <th>Correo</th>                      
                    </tr>
                  </thead>
                  <?= $this->clientes ?>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>