<div class="container-fluid" style="height: 75vh">
    <h2 class="col-md-12 text-center">New User Signup!</h2>
    <div class="col-md-12">
        <form class="border form-style row" style="width:60%;margin:auto">
			<div class="col-md-6">
			<div class="form-group">
					<label for="createNombres">Nombres</label>
					<input type="text" class="form-control" placeholder="Nombres" required>
				</div>
				<div class="form-group">
					<label for="createApellidos">Apellidos</label>
					<input type="text" class="form-control" placeholder="Apellidos" required>
				</div>
				<div class="form-group">
					<label for="createTelefono">Telefono</label>
					<input type="text" class="form-control" placeholder="Telefono" required>
				</div>
				<div class="form-group">
					<label for="createDireccion">Dirección</label>
					<input type="text" class="form-control" placeholder="Direccion" required>
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group">
					<label for="createCedula">Cedula</label>
					<input type="text" class="form-control" placeholder="Cedula" required>
				</div>
				<div class="form-group">
					<label for="createNombreUsuario">Nombre de usuario</label>
					<input type="text" class="form-control" placeholder="Nombre de usuario" required>
				</div>
				<div class="form-group">
					<label for="createCorreo">Correo</label>
					<input type="email" class="form-control" placeholder="Correo" required>
				</div>
				<div class="form-group">
					<label for="createPassword">Contraseña</label>
					<input type="password" class="form-control" placeholder="Contraseña" required>
				</div>
			</div>
				
			<div class="form-group col-md-12">
				<button type="submit" class="btn btn-default">Crear cuenta</button>
			</div>
        </form>
    </div>
</div>