    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Trabajadores</h1>
    <p class="mb-4">
      En este modulo se refleja la informacion general de los trabajadores del sistema.
    </p>
    
    <!-- divisor -->
    <div class="row">
        <!-- registro de un nuevo trabajador -->
        <div class="col-lg-5 border p-3 bg-white">
            <form method="post" class="row registro-trabajador" id="AddTrabajador">

                <h5 class="col-lg-12 border-bottom my-1 p-2">Agregar Trabajador</h5>
                <div class="form-group col-md-6">
                    <label for="nombre">Nombre</label>
                    <input type="text" name="nombre" id="nombre" class="form-control" placeholder="Nombre" required autocomplete="off">
                </div>
                <div class="form-group col-md-6">
                    <label for="apellido">Apellido</label>
                    <input type="text" name="apellido" id="apellido" class="form-control" placeholder="Apellido" required autocomplete="off">
                </div>
                <div class="form-group col-md-6">
                    <label for="nombreUsuario">Nombre Usuario</label>
                    <input type="text" name="nombreUsuario" id="nombreUsuario" class="form-control" placeholder="Nombre usuario" required autocomplete="off">
                    <div class="repetido"></div>
                </div>

                <div class="form-group col-md-6">
                    <label for="direccion">Direccion</label>
                    <input type="text" name="direccion" id="direccion" class="form-control" placeholder="Direccion" required autocomplete="off">
                </div>

                <div class="form-group col-md-6">
                    <label for="telefono">Telefono</label>
                    <input type="text" name="telefono" id="telefono" class="form-control telefonoTra" placeholder="Telefono" required autocomplete="off">
                </div>

                <div class="form-group col-md-6">
                    <label for="correo">Correo</label>
                    <input type="email" name="correo" id="correo" class="form-control" placeholder="Correo Electronico" required autocomplete="off">
                    <div class="repetidoCorreo"></div>
                </div>

                <div class="form-group col-md-6">
                    <label for="pass">Contraseña</label>
                    <input type="password" name="pass" id="pass" class="form-control" placeholder="Contraseña" required autocomplete="off">
                    <div class="progress progress-xxs mt-1">
                        <div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" arial-valuenow="0" arial-valuemin="0" arial-valuemax="100"></div>
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <label for="pass">Rol</label>
                    <select name="rol" id="rol" class="form-control">
                        <?= $this->roles ?>
                    </select>
                </div>

                <div class="form-group col-md-6">
                    <input type="submit" value="Agregar" estado="false" disabled="disabled" class="btn btn-primary btn-block btnAgregar" id="btnAgregarUsu" required>
                </div>
            </form>
        </div>

        <!-- informacion del trabajador -->
        <div class="col-lg-7">

        <div class="card">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Todos</h6>
              </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="trabaja table table-bordered table-sm text-center text-gray-800 text-md nuevosProductos" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Nombre</th>
                      <th>Apellido</th>
                      <th>Ver</th>
                      <th>Actualizar</th>
                      <th>Eliminar</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>ID</th>
                      <th>Nombre</th>
                      <th>Apellido</th>
                      <th>Ver</th>
                      <th>Actualizar</th>
                      <th>Eliminar</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    <?=$this->contenido;?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
    </div>

